/**
 * Database Types
 *
 * This file will be auto-generated by Supabase CLI
 * Run: npx supabase gen types typescript --local > lib/supabase/database.types.ts
 *
 * For now, we define types manually for all CMS tables
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type ProjectStatus = 'pending' | 'in_progress' | 'completed'

export interface Database {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string
          title: string
          status: ProjectStatus
          is_visible: boolean
          summary: string | null
          image_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          status?: ProjectStatus
          is_visible?: boolean
          summary?: string | null
          image_url?: string | null
        }
        Update: {
          id?: string
          title?: string
          status?: ProjectStatus
          is_visible?: boolean
          summary?: string | null
          image_url?: string | null
        }
        Relationships: []
      }
      products: {
        Row: {
          id: string
          slug: string
          icon: string
          title: string
          description: string | null
          long_description: string | null
          content: string | null
          specifications: Json
          image_url: string | null
          sort_order: number
          is_visible: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          icon?: string
          title: string
          description?: string | null
          long_description?: string | null
          content?: string | null
          specifications?: Json
          image_url?: string | null
          sort_order?: number
          is_visible?: boolean
        }
        Update: {
          id?: string
          slug?: string
          icon?: string
          title?: string
          description?: string | null
          long_description?: string | null
          content?: string | null
          specifications?: Json
          image_url?: string | null
          sort_order?: number
          is_visible?: boolean
        }
        Relationships: []
      }
      product_features: {
        Row: {
          id: string
          product_id: string
          title: string
          description: string | null
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          title: string
          description?: string | null
          sort_order?: number
        }
        Update: {
          id?: string
          product_id?: string
          title?: string
          description?: string | null
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: 'product_features_product_id_fkey'
            columns: ['product_id']
            referencedRelation: 'products'
            referencedColumns: ['id']
          }
        ]
      }
      product_images: {
        Row: {
          id: string
          product_id: string
          image_url: string
          alt_text: string | null
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          image_url: string
          alt_text?: string | null
          sort_order?: number
        }
        Update: {
          id?: string
          product_id?: string
          image_url?: string
          alt_text?: string | null
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: 'product_images_product_id_fkey'
            columns: ['product_id']
            referencedRelation: 'products'
            referencedColumns: ['id']
          }
        ]
      }
      service_categories: {
        Row: {
          id: string
          title: string
          slug: string
          icon: string
          description: string | null
          image_url: string | null
          sort_order: number
          is_visible: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          icon?: string
          description?: string | null
          image_url?: string | null
          sort_order?: number
          is_visible?: boolean
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          icon?: string
          description?: string | null
          image_url?: string | null
          sort_order?: number
          is_visible?: boolean
        }
        Relationships: []
      }
      services: {
        Row: {
          id: string
          icon: string
          title: string
          description: string | null
          details: Json
          sort_order: number
          is_visible: boolean
          created_at: string
          updated_at: string
          category_id: string | null
          slug: string | null
          content: string | null
          detail_image_url: string | null
          image_url: string | null
        }
        Insert: {
          id?: string
          icon?: string
          title: string
          description?: string | null
          details?: Json
          sort_order?: number
          is_visible?: boolean
          category_id?: string | null
          slug?: string | null
          content?: string | null
          detail_image_url?: string | null
          image_url?: string | null
        }
        Update: {
          id?: string
          icon?: string
          title?: string
          description?: string | null
          details?: Json
          sort_order?: number
          is_visible?: boolean
          category_id?: string | null
          slug?: string | null
          content?: string | null
          detail_image_url?: string | null
          image_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'services_category_id_fkey'
            columns: ['category_id']
            referencedRelation: 'service_categories'
            referencedColumns: ['id']
          }
        ]
      }
      standards: {
        Row: {
          id: string
          icon: string
          acronym: string | null
          full_name: string | null
          title: string
          description: string | null
          features: Json
          category: string
          az_name: string | null
          normal_range: string | null
          measurement: string | null
          sort_order: number
          is_visible: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          icon?: string
          acronym?: string | null
          full_name?: string | null
          title: string
          description?: string | null
          features?: Json
          category?: string
          az_name?: string | null
          normal_range?: string | null
          measurement?: string | null
          sort_order?: number
          is_visible?: boolean
        }
        Update: {
          id?: string
          icon?: string
          acronym?: string | null
          full_name?: string | null
          title?: string
          description?: string | null
          features?: Json
          category?: string
          az_name?: string | null
          normal_range?: string | null
          measurement?: string | null
          sort_order?: number
          is_visible?: boolean
        }
        Relationships: []
      }
      team_members: {
        Row: {
          id: string
          name: string
          role: string
          bio: string | null
          image_url: string | null
          linkedin_url: string | null
          sort_order: number
          is_visible: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          role: string
          bio?: string | null
          image_url?: string | null
          linkedin_url?: string | null
          sort_order?: number
          is_visible?: boolean
        }
        Update: {
          id?: string
          name?: string
          role?: string
          bio?: string | null
          image_url?: string | null
          linkedin_url?: string | null
          sort_order?: number
          is_visible?: boolean
        }
        Relationships: []
      }
      contact_submissions: {
        Row: {
          id: string
          full_name: string
          email: string
          phone: string | null
          subject: string | null
          message: string
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          full_name: string
          email: string
          phone?: string | null
          subject?: string | null
          message: string
          is_read?: boolean
        }
        Update: {
          id?: string
          full_name?: string
          email?: string
          phone?: string | null
          subject?: string | null
          message?: string
          is_read?: boolean
        }
        Relationships: []
      }
      site_settings: {
        Row: {
          key: string
          value: Json
          updated_at: string
        }
        Insert: {
          key: string
          value: Json
        }
        Update: {
          key?: string
          value?: Json
        }
        Relationships: []
      }
      support_types: {
        Row: {
          id: string
          title: string
          slug: string
          description: string | null
          content: string | null
          image_url: string | null
          sort_order: number
          is_visible: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          description?: string | null
          content?: string | null
          image_url?: string | null
          sort_order?: number
          is_visible?: boolean
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          description?: string | null
          content?: string | null
          image_url?: string | null
          sort_order?: number
          is_visible?: boolean
        }
        Relationships: []
      }
      news: {
        Row: {
          id: string
          title: string
          slug: string
          summary: string | null
          content: string | null
          image_url: string | null
          published_at: string
          is_visible: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          summary?: string | null
          content?: string | null
          image_url?: string | null
          published_at?: string
          is_visible?: boolean
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          summary?: string | null
          content?: string | null
          image_url?: string | null
          published_at?: string
          is_visible?: boolean
        }
        Relationships: []
      }
      admin_users: {
        Row: {
          id: string
          created_at: string
        }
        Insert: {
          id: string
        }
        Update: {
          id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      project_status: ProjectStatus
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
